pluginGroup = com.github.arm092.apricodemonokai
pluginName = Apricode Monokai
pluginRepositoryUrl = https://github.com/arm092/apricode-monokai
pluginVersion = 3.0.3

pluginSinceBuild = 262
platformVersion = 2026.2.0.1
platformType = IU
pluginVerifierCommunityVersions =
pluginVerifierIdeaVersions = 2026.2.0.1
pluginVerifierEapBuild = 263

org.gradle.configuration-cache = true
org.gradle.caching = true
